version: '3.8'
services:
  frontend:
    build: ./react-docker
    container_name: my-app
    ports:
      - '3000:3000'
    volumes:
      - ./react-docker/src:/app/src
    stdin_open: true
    tty: true